name: Build and deploy Python app to Azure Web App - backend-0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - run: |
          zip -r app.zip . -x "*.git*" "__pycache__/*" "*.pytest_cache*" "*.github/*" "requirements.txt"

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-0'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1E44DD5F3D22408390A184658AAABEBC }}
          package: app.zip



